### ISSUE TITLE
Chrome binary not found error

### ISSUE THREAD

**Issue by justpentest** [mdhama/lazyshot#1]
Hi 
I am getting the following error:
I have downloaded and given 755 and +x permission to chrome binary. I am not sure what is the problem. Chrome drivers is in the same folder as well.

Traceback (most recent call last):
  File "lazyshot.py", line 80, in <module>
    result = takeScreeshot(url)
  File "lazyshot.py", line 70, in takeScreeshot
    driver = webdriver.Chrome(executable_path=os.path.abspath("chromedriver"), chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.9.248316,platform=Linux 4.12.0-kali1-686-pae x86)

**Comment by mdhama** [comment]
Can you tell me the output of command `chromedriver --v`?

**Comment by justpentest** [comment]
Hi 
root@justpentest:~/Desktop/tools/lazyshot# ./chromedriver --v
Starting ChromeDriver (v2.9.248316) on port 9515

root@justpentest:~/Desktop/tools/lazyshot# uname -a
Linux justpentest 4.12.0-kali1-686-pae #1 SMP Debian 4.12.6-1kali6 (2017-08-30) i686 GNU/Linux

**Comment by mdhama** [comment]
It seems like you are not added the PATH in .bash_profile, file please check the documentation. `chromedriver` command should be work globally.

**Comment by justpentest** [comment]
I have set bash_profile and I am able to execute chromedriver from any folder

root@justpentest:/etc# chrome  [tab][tab]
chrome-gnome-shell        chromedriver              chromedriver_linux32.zip  chromeos-tpm-recovery     
root@justpentest:/etc# chromedriver
Starting ChromeDriver (v2.9.248316) on port 9515
^C
root@justpentest:/etc# 
THe command"chromedriver" is working globally.

**Comment by mdhama** [comment]
I'm not able to reproduce this issue. I think it's a client-side issue. You can check [here](https://sites.google.com/a/chromium.org/chromedriver/getting-started) if you missing something while installing.
