### ISSUE TITLE
bash_profile not found

### ISSUE THREAD

**Issue by Anirbansingha1** [mdhama/lazyshot#2]
Hey @mdhama ,
It's look's like awesome tool, I want to use it but when I want to download and install I noticed that for installation I should download chrome driver and paste a command in .bash_profile But unfortunately I didn't find in my kali linux. Can you please tell me  how to do it?
Thanks in advanced :)

**Comment by mdhama** [comment]
Hey @Anirbansingha1,
You can find `.bash_profile` or `.bashrc` file in `/root` or `/username/home` directory. 
Please feel free to ask if any query.
